### PR TITLE
Ch fix front tests 141393701

### PR DESCRIPTION
**Pull request by mugiwaramunyi**
Fixed the following tests in front end module.
-test_add_channel
-test_add_check
-test_add_pushbover

### CODE REVIEW

**Comment by andela-sjames** [comment]
Please review this again and check my comments @Jonathan-Ngondi

**Comment by mugiwaramunyi** [comment]
@andela-sjames Are the comments in the codebase?

**Comment by andela-sjames** [comment]
The comments are for the Pull request @Jonathan-Ngondi you may want to check your mail to see the details.

**Comment by mugiwaramunyi** [comment]
@andela-sjames Resolved all perceived redundancies and cleaned up the relevant code. 👍

**Pull request merged**
